-- ============================================================
-- Migración: Cuentas de dinero (financial_accounts)
-- Cuentas Claras App
--
-- Agrega:
--   1) Tabla financial_accounts (bancos, billeteras digitales, efectivo).
--      name e initial_balance se almacenan cifrados (AES-256-GCM Base64),
--      por eso son VARCHAR como el resto de columnas sensibles.
--   2) Columna account_id (nullable) en financial_records, con FK a la cuenta.
--      Los movimientos históricos quedan con account_id NULL (sin cuenta).
--
-- Idempotente: se puede ejecutar varias veces sin error.
-- Ejecutar UNA vez sobre la base Supabase/PostgreSQL.
-- ============================================================

CREATE TABLE IF NOT EXISTS financial_accounts (
    account_id           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_document_number VARCHAR(12)   NOT NULL,
    name                 VARCHAR(1024) NOT NULL,
    type                 VARCHAR(20)   NOT NULL,
    provider             VARCHAR(50),
    initial_balance      VARCHAR(255)  NOT NULL,
    color                VARCHAR(20),
    icon                 VARCHAR(50),
    archived             BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP     NOT NULL,
    updated_at           TIMESTAMP,
    CONSTRAINT pk_financial_accounts PRIMARY KEY (account_id),
    CONSTRAINT fk_fa_user FOREIGN KEY (user_document_number) REFERENCES users (document_number)
);

ALTER TABLE financial_records ADD COLUMN IF NOT EXISTS account_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fr_account') THEN
        ALTER TABLE financial_records
            ADD CONSTRAINT fk_fr_account FOREIGN KEY (account_id)
                REFERENCES financial_accounts (account_id);
    END IF;
END$$;

-- Reinicio de secuencia IDENTITY (solo necesario si se migran datos con IDs fijos):
-- SELECT setval(pg_get_serial_sequence('financial_accounts','account_id'), COALESCE((SELECT MAX(account_id) FROM financial_accounts), 1));
