-- ============================================================
-- Esquema completo en PostgreSQL (Supabase) — Cuentas Claras App
-- Reconstruido desde las entidades JPA (fuente de verdad del modelo).
--
-- Uso: ejecutar UNA vez sobre la base Supabase vacía (SQL Editor del panel
-- o psql). Después de cargar los datos con pgloader, correr el bloque final
-- "REINICIO DE SECUENCIAS IDENTITY".
--
-- Notas de tipos:
--   - Las columnas cifradas (AES-256-GCM en Base64) son VARCHAR/TEXT normales.
--   - LocalDate -> DATE ; java.util.Date -> TIMESTAMP (igual que mapea Hibernate).
--   - Los IDs autogenerados usan IDENTITY BY DEFAULT para permitir insertar los
--     valores existentes durante la migración de datos.
-- ============================================================

-- 1) roles
CREATE TABLE roles (
    role_code   VARCHAR(3)   NOT NULL,
    role_name   VARCHAR(250) NOT NULL,
    description VARCHAR(250),
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP,
    CONSTRAINT pk_roles PRIMARY KEY (role_code)
);

-- 2) permissions
CREATE TABLE permissions (
    permission_code VARCHAR(5)   NOT NULL,
    permission_name VARCHAR(250) NOT NULL,
    description     VARCHAR(250),
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT pk_permissions PRIMARY KEY (permission_code)
);

-- 3) roles_permissions (PK compuesta)
CREATE TABLE roles_permissions (
    role_code       VARCHAR(3) NOT NULL,
    permission_code VARCHAR(5) NOT NULL,
    created_at      TIMESTAMP  NOT NULL,
    updated_at      TIMESTAMP,
    CONSTRAINT pk_roles_permissions PRIMARY KEY (role_code, permission_code),
    CONSTRAINT fk_rp_role       FOREIGN KEY (role_code)       REFERENCES roles (role_code),
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_code) REFERENCES permissions (permission_code)
);

-- 4) users
CREATE TABLE users (
    document_number       VARCHAR(12)  NOT NULL,
    document_type         VARCHAR(3)   NOT NULL,
    role_code             VARCHAR(3)   NOT NULL,
    name                  VARCHAR(250) NOT NULL,
    last_name             VARCHAR(250) NOT NULL,
    email                 VARCHAR(250) NOT NULL,
    cel_number            VARCHAR(12),
    birth_date            TIMESTAMP,
    password              VARCHAR(255),
    auth_provider         VARCHAR(10)  NOT NULL DEFAULT 'LOCAL',
    google_sub            VARCHAR(64),
    locked                BOOLEAN      NOT NULL,
    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP,
    CONSTRAINT pk_users      PRIMARY KEY (document_number),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_code) REFERENCES roles (role_code)
);

-- 5) budget_cycles
CREATE TABLE budget_cycles (
    id                   BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    user_document_number VARCHAR(12) NOT NULL,
    start_date           DATE        NOT NULL,
    end_date             DATE        NOT NULL,
    payment_day          INTEGER     NOT NULL,
    periodicity          VARCHAR(20) NOT NULL,
    status               VARCHAR(20) NOT NULL,
    created_at           TIMESTAMP   NOT NULL,
    updated_at           TIMESTAMP,
    CONSTRAINT pk_budget_cycles PRIMARY KEY (id),
    CONSTRAINT fk_bc_user FOREIGN KEY (user_document_number) REFERENCES users (document_number)
);

-- 6) budget_categories (category_name y assigned_amount cifrados)
CREATE TABLE budget_categories (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    cycle_id        BIGINT        NOT NULL,
    category_name   VARCHAR(1024) NOT NULL,
    assigned_amount VARCHAR(255)  NOT NULL,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP,
    CONSTRAINT pk_budget_categories PRIMARY KEY (id),
    CONSTRAINT fk_bcat_cycle FOREIGN KEY (cycle_id) REFERENCES budget_cycles (id)
);

-- 7) user_budget_config
CREATE TABLE user_budget_config (
    id                   BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    user_document_number VARCHAR(12) NOT NULL,
    payment_day          INTEGER     NOT NULL,
    periodicity          VARCHAR(20) NOT NULL,
    next_payment_date    DATE,
    created_at           TIMESTAMP   NOT NULL,
    updated_at           TIMESTAMP,
    CONSTRAINT pk_user_budget_config PRIMARY KEY (id),
    CONSTRAINT uk_ubc_user UNIQUE (user_document_number),
    CONSTRAINT fk_ubc_user FOREIGN KEY (user_document_number) REFERENCES users (document_number)
);

-- 8) fixed_budget_category (category_name y amount cifrados)
CREATE TABLE fixed_budget_category (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_budget_config_id BIGINT        NOT NULL,
    category_name         VARCHAR(1024) NOT NULL,
    amount                VARCHAR(255)  NOT NULL,
    CONSTRAINT pk_fixed_budget_category PRIMARY KEY (id),
    CONSTRAINT fk_fbc_config FOREIGN KEY (user_budget_config_id)
        REFERENCES user_budget_config (id) ON DELETE CASCADE
);

-- 8b) financial_accounts (name e initial_balance cifrados)
CREATE TABLE financial_accounts (
    account_id           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_document_number VARCHAR(12)   NOT NULL,
    name                 VARCHAR(1024) NOT NULL,
    type                 VARCHAR(20)   NOT NULL,
    provider             VARCHAR(50),
    initial_balance      VARCHAR(255)  NOT NULL,
    color                VARCHAR(20),
    icon                 VARCHAR(50),
    archived             BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP     NOT NULL,
    updated_at           TIMESTAMP,
    CONSTRAINT pk_financial_accounts PRIMARY KEY (account_id),
    CONSTRAINT fk_fa_user FOREIGN KEY (user_document_number) REFERENCES users (document_number)
);

-- 9) financial_records (description y amount cifrados)
CREATE TABLE financial_records (
    financial_record_id BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_document_number VARCHAR(12)   NOT NULL,
    record_type          VARCHAR(20)   NOT NULL,
    budget_category_id   BIGINT,
    account_id           BIGINT,
    budget_cycle_id      BIGINT,
    description          VARCHAR(1024),
    amount               VARCHAR(255)  NOT NULL,
    record_date          DATE          NOT NULL,
    recurring            BOOLEAN       NOT NULL,
    periodicity          VARCHAR(20),
    created_at           TIMESTAMP     NOT NULL,
    updated_at           TIMESTAMP,
    CONSTRAINT pk_financial_records PRIMARY KEY (financial_record_id),
    CONSTRAINT fk_fr_user FOREIGN KEY (user_document_number) REFERENCES users (document_number),
    CONSTRAINT fk_fr_category FOREIGN KEY (budget_category_id) REFERENCES budget_categories (id),
    CONSTRAINT fk_fr_account FOREIGN KEY (account_id) REFERENCES financial_accounts (account_id),
    CONSTRAINT fk_fr_cycle FOREIGN KEY (budget_cycle_id) REFERENCES budget_cycles (id)
);

-- Acelera GET /financial-records/cycles/{cycleId}. budget_cycle_id se estampa con
-- el ciclo ACTIVO del usuario al crear el movimiento; los históricos quedan NULL.
CREATE INDEX IF NOT EXISTS ix_fr_budget_cycle ON financial_records (budget_cycle_id);

-- 10) debts (creditor, description, initial_amount, pending_amount cifrados)
CREATE TABLE debts (
    debt_id              BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_document_number VARCHAR(12)   NOT NULL,
    creditor             VARCHAR(1024) NOT NULL,
    description          VARCHAR(1024),
    initial_amount       VARCHAR(255)  NOT NULL,
    pending_amount       VARCHAR(255)  NOT NULL,
    start_date           DATE          NOT NULL,
    due_date             DATE,
    status               VARCHAR(20)   NOT NULL,
    created_at           TIMESTAMP     NOT NULL,
    updated_at           TIMESTAMP,
    CONSTRAINT pk_debts PRIMARY KEY (debt_id),
    CONSTRAINT fk_debt_user FOREIGN KEY (user_document_number) REFERENCES users (document_number)
);

-- 11) financial_goals (name, description, target_amount, current_amount cifrados)
CREATE TABLE financial_goals (
    financial_goal_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_document_number VARCHAR(12)   NOT NULL,
    name                 VARCHAR(1024) NOT NULL,
    description          VARCHAR(1024),
    target_amount        VARCHAR(255)  NOT NULL,
    current_amount       VARCHAR(255)  NOT NULL,
    start_date           DATE          NOT NULL,
    target_date          DATE          NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    created_at           TIMESTAMP     NOT NULL,
    updated_at           TIMESTAMP,
    CONSTRAINT pk_financial_goals PRIMARY KEY (financial_goal_id),
    CONSTRAINT fk_fg_user FOREIGN KEY (user_document_number) REFERENCES users (document_number)
);

-- 12) ai_coach_requests (question y ai_response cifrados)
CREATE TABLE ai_coach_requests (
    ai_coach_request_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    user_document_number VARCHAR(12)   NOT NULL,
    financial_goal_id    BIGINT,
    question             VARCHAR(2048) NOT NULL,
    financial_context    TEXT,
    ai_response          TEXT          NOT NULL,
    model                VARCHAR(100)  NOT NULL,
    created_at           TIMESTAMP     NOT NULL,
    CONSTRAINT pk_ai_coach_requests PRIMARY KEY (ai_coach_request_id),
    CONSTRAINT fk_acr_user FOREIGN KEY (user_document_number) REFERENCES users (document_number),
    CONSTRAINT fk_acr_goal FOREIGN KEY (financial_goal_id)    REFERENCES financial_goals (financial_goal_id)
);

-- ============================================================
-- REINICIO DE SECUENCIAS IDENTITY
-- Ejecutar DESPUÉS de cargar los datos con pgloader, para que los próximos
-- INSERT no choquen con los IDs ya migrados. (Sin datos, no hace daño correrlo.)
-- ============================================================
-- SELECT setval(pg_get_serial_sequence('budget_cycles','id'),               COALESCE((SELECT MAX(id) FROM budget_cycles), 1));
-- SELECT setval(pg_get_serial_sequence('budget_categories','id'),           COALESCE((SELECT MAX(id) FROM budget_categories), 1));
-- SELECT setval(pg_get_serial_sequence('user_budget_config','id'),          COALESCE((SELECT MAX(id) FROM user_budget_config), 1));
-- SELECT setval(pg_get_serial_sequence('fixed_budget_category','id'),       COALESCE((SELECT MAX(id) FROM fixed_budget_category), 1));
-- SELECT setval(pg_get_serial_sequence('financial_records','financial_record_id'), COALESCE((SELECT MAX(financial_record_id) FROM financial_records), 1));
-- SELECT setval(pg_get_serial_sequence('debts','debt_id'),                  COALESCE((SELECT MAX(debt_id) FROM debts), 1));
-- SELECT setval(pg_get_serial_sequence('financial_goals','financial_goal_id'), COALESCE((SELECT MAX(financial_goal_id) FROM financial_goals), 1));
-- SELECT setval(pg_get_serial_sequence('ai_coach_requests','ai_coach_request_id'), COALESCE((SELECT MAX(ai_coach_request_id) FROM ai_coach_requests), 1));
